# Generated by Django 4.1.1 on 2022-10-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='font',
        ),
        migrations.AddField(
            model_name='notes',
            name='label',
            field=models.ManyToManyField(related_name='label', to='notes.label'),
        ),
    ]
